import { test, expect } from '@playwright/test';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

test.describe('Document Ingestion', () => {
  test('should upload and ingest a markdown file successfully', async ({ page }) => {
    // 1. Navigate to home
    await page.goto('/');
    await expect(page).toHaveTitle(/Qurio/);

    // 2. Click File Upload Tab
    await page.getByRole('button', { name: 'File Upload' }).click();
    await expect(page.getByText('Select Document')).toBeVisible();

    // 3. Upload File
    // Create a virtual file for the test
    const fileContent = '# Automated Test Doc\n\nThis is a test document created by Playwright e2e tests.\n';
    await page.setInputFiles('input[type="file"]', {
      name: 'e2e-test.md',
      mimeType: 'text/markdown',
      buffer: Buffer.from(fileContent)
    });

    // 4. Click Upload & Ingest
    const uploadBtn = page.getByRole('button', { name: 'Upload & Ingest' });
    await expect(uploadBtn).toBeEnabled();
    await uploadBtn.click();

    // 5. Verify Status Transition
    // It might start as pending/in_progress, wait for completed
    // We look for a badge within a card that contains our filename
    const sourceCard = page.locator('.rounded-xl', { hasText: 'e2e-test.md' }).first();
    
    // Wait for the status badge to say 'completed'
    // Increase timeout because ingestion might take a moment
    await expect(sourceCard).toContainText('completed', { timeout: 30000 });

    // 6. Verify Details Page
    await sourceCard.getByRole('button', { name: 'View Details' }).click();
    
    // Verify we are on details page
    await expect(page.getByRole('heading', { name: 'Source Details' })).toBeVisible();
    await expect(page.getByText('e2e-test.md')).toBeVisible();
    
    // Verify chunks content matches what we uploaded
    await expect(page.getByText('# Automated Test Doc')).toBeVisible();
  });

  test('should upload and ingest a PDF file successfully', async ({ page }) => {
    // 1. Generate Valid PDF
    const pdfDoc = await PDFDocument.create();
    const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
    const page1 = pdfDoc.addPage();
    const { width, height } = page1.getSize();
    page1.drawText('This is a test PDF generated by Playwright.', {
      x: 50,
      y: height - 4 * 50,
      size: 30,
      font: timesRomanFont,
      color: rgb(0, 0.53, 0.71),
    });
    const pdfBytes = await pdfDoc.save();

    // 2. Navigate to home
    await page.goto('/');

    // 3. Click File Upload Tab
    await page.getByRole('button', { name: 'File Upload' }).click();

    // 4. Upload File
    await page.setInputFiles('input[type="file"]', {
      name: 'e2e-test.pdf',
      mimeType: 'application/pdf',
      buffer: Buffer.from(pdfBytes)
    });

    // 5. Click Upload & Ingest
    const uploadBtn = page.getByRole('button', { name: 'Upload & Ingest' });
    await expect(uploadBtn).toBeEnabled();
    await uploadBtn.click();

    // 6. Verify Status Transition
    const sourceCard = page.locator('.rounded-xl', { hasText: 'e2e-test.pdf' }).first();
    await expect(sourceCard).toContainText('completed', { timeout: 45000 }); // Longer timeout for PDF processing

    // 7. Verify Details Page
    await sourceCard.getByRole('button', { name: 'View Details' }).click();
    
    // Verify chunk content (Docling should extract the text)
    await expect(page.getByText('This is a test PDF generated by Playwright')).toBeVisible({ timeout: 10000 });
  });
});
